dist: trusty

language: java

jdk:
  - oraclejdk8
  - openjdk8
  - openjdk11
  - oraclejdk11

after_success:
  - if [ -e ./gradlew ];then ./gradlew check;else gradle check;fi
  - bash <(curl -s https://codecov.io/bash)
